config/routes.rb
Rails.application.routes.draw do
  resources :sellers
  get '/buyers/stats', to: 'buyers#stats', as: 'buyer_stats'
  resources :buyers
  resources :swipes
  resources :wishlists
  get 'sessions/new'
  resources :listings
  resources :clubs
  resources :products


  get   '/login', to: 'sessions#splash'
  patch  '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/carts', to: 'carts#update', as: 'add_listing_to_cart'
  get '/carts', to: 'carts#index', as: 'carts'
  delete '/carts', to: 'carts#destroy', as: 'clear_cart'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seller.rb
class Seller < ApplicationRecord
  has_secure_password validation: false
  has_many :products
  has_many :listings, through: :products
  has_many :club_sellers
  has_many :clubs, through: :club_sellers


  validates :first_name, :last_name, presence: true
  validates :email, :username, uniqueness: true
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :find_seller, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorized, only: [:new, :create]

  def index
    @sellers = Seller.all
  end

  def show
  end

  def new
    @seller = Seller.new
  end

  def create
    @seller = Seller.create(new_seller_params)
    if @seller.valid?

      redirect_to seller_path(@seller)
    else
      flash[:error] = @seller.errors.full_messages
      redirect_to new_seller_path
    end
  end

  def edit
  end

  def update
    @seller.update(new_seller_params)
    if @seller.valid?
      redirect_to seller_path(@seller)
    else
      flash[:error] = @seller.errors.full_messages
      redirect_to edit_seller_path(@seller)
    end
  end

  def destroy
    @seller.destroy
    redirect_to sellers_path
  end

  private

  def new_seller_params
    params.require(:seller).permit(:first_name, :last_name, :password, :email, :username)
  end

  def find_seller
    @seller = Seller.find(params[:id])
  end

end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.erb
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>


<%= form_for @seller do |f| %>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <%= f.submit %>
  <% end %>

app/views/sellers/edit.erb
<h1><font size="5" class= "fire-text">Check Yourself!</font></h1>
<p><button><%= link_to 'My Page', seller_path(session[:seller_id]) %></button></p>

<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>

<style>
  body{
    background-image: url("https://media.giphy.com/media/nKERd2uhn8hhe/giphy.gif");
    background-repeat: no-repeat;
    background-color: #cccccc;
    background-size: cover;
    vertical-align: middle;
    text-align:center;
  }
  p {
    text-align: right;
  }
 }
 </style>

  <%= render 'form' %>

app/views/sellers/index.erb
<h1> INDEX </h1>

<% @sellers.each do |seller| %>
  <%= link_to seller.username, seller %><br>
  <% end %>

app/views/sellers/new.erb
<h1><font size="5" class= "fire-text">Create Your Account</font></h1>

<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>

<style>
  body{
    background-image: url("https://media.giphy.com/media/nKERd2uhn8hhe/giphy.gif");
    background-repeat: no-repeat;
    background-color: #cccccc;
    background-size: cover;
    vertical-align: middle;
    text-align:center;
  }
 }
 </style>
  <%= render 'form' %>

app/views/sellers/show.erb
<h1><font size="5" class= "fire-text">Shop or Drop</font></h1>

<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>


<style>
  body{
    background-image: url("https://media.giphy.com/media/nKERd2uhn8hhe/giphy.gif");
    background-repeat: no-repeat;
    background-color: #cccccc;
    background-size: cover;
    vertical-align: middle;
    text-align:center;
  }
 }
 </style>

  <p> <span style="font-weight:bold;">First Name: </span> <%= @seller.first_name %></p>
  <p><span style="font-weight:bold;">Last Name: </span><%= @seller.last_name %> </p>
  <p><span style="font-weight:bold;">Username: </span><%= @seller.username %> </p>
  <p><span style="font-weight:bold;">Email: </span><%= @seller.email %></p>

    <button><%= link_to 'Edit Account', edit_seller_path %></button>
    <button><%= link_to 'New Listing', new_listing_path %></button>
    <button><%= link_to 'New Product', new_product_path %></button>
    <button><%= link_to 'Your Listings', listings_path %></button>
    <button><%= link_to 'Your Products', products_path%></button>
    <button><%= button_to "Delete Account", @seller, method: :delete, data: { confirm: "Are you sure you want to delete your account?" } %></button>
    <button><%= button_to "Logout", logout_path, method: :delete, data: { confirm: "Are you sure you want to log out?" } %> </button>