config/routes.rb
Rails.application.routes.draw do
  resources :sellers
  get '/buyers/stats', to: 'buyers#stats', as: 'buyer_stats'
  resources :buyers
  resources :swipes
  resources :wishlists
  get 'sessions/new'
  resources :listings
  resources :clubs
  resources :products


  get   '/login', to: 'sessions#splash'
  patch  '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/carts', to: 'carts#update', as: 'add_listing_to_cart'
  get '/carts', to: 'carts#index', as: 'carts'
  delete '/carts', to: 'carts#destroy', as: 'clear_cart'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/buyer.rb
class Buyer < ApplicationRecord
  has_many :swipes
  # has_many :payments
  # has_one :cart
  # has_one :do_not_want_list
  has_many :wishlists
  has_secure_password validation: false

  validates :first_name, :last_name, presence:true
  validates :email, :username, uniqueness: true

  # def self.login(password, email)
  #   self.find()
  # end

  def password
  end

  def all_swiped_items
    output = self.swipes.collect do |swipe|
      swipe.product_id
    end

    if(output == nil)
      output = []
    end

    output

  end

  def total_swipes
    self.swipes.count
  end

  def total_like_swipes
    array = self.swipes.select do |swipe|
      if(swipe.outcome == "like")
        swipe
      end
    end

    array.count
  end

  def total_dislike_swipes
    array = self.swipes.select do |swipe|
      if(swipe.outcome == "dislike")
        swipe
      end
    end


    array.count
  end

  def total_superlike_swipes
    array = self.swipes.select do |swipe|
      if(swipe.outcome == "superlike")
        swipe
      end
    end

    array.count

  end

  def total_positive_swipes
    total_like_swipes + total_superlike_swipes
  end

  def total_percent_positive
    ( total_positive_swipes.to_f / total_swipes) * 100
  end

  def get_swipe_stats
    swipes = self.swipes
  end




end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
    before_action :find_buyer, only: [:show, :edit, :update, :destroy]
    skip_before_action :authorized, only: [:new, :create]

  def index
    @buyers = Buyer.all
  end

  def show
    @listings = cart.map do |listing_id|
      Listing.find(listing_id)
    end
  end

  def new
    @buyer = Buyer.new
  end

  def create
    @buyer = Buyer.create(new_buyer_params)
    if @buyer.valid?
      flash[:notice] = "Your account has been successfully created!"
      redirect_to '/login'
    else
      flash[:error] = @buyer.errors.full_messages
      redirect_to new_buyer_path
    end
  end

  def edit
  end

  def update
    @buyer.update(new_buyer_params)
    if @buyer.valid?
      redirect_to buyer_path(@buyer)
    else
      flash[:error] = @buyer.errors.full_messages
      redirect_to edit_buyer_path(@buyer)
    end
  end

  def destroy
    @buyer.destroy
    logout
  end

  def stats
    @buyer = Buyer.find(session[:buyer_id])
     render 'stats'
  end

  private

  def new_buyer_params

    params.require(:buyer).permit(:first_name, :last_name, :password, :email, :username)
  end

  def find_buyer

    @buyer = Buyer.find(params[:id])
  end

end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/views/buyers/_form.erb
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>

<body>
<%= form_for @buyer do |f| %>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <%= f.submit %>
  <% end %>
</body>

app/views/buyers/edit.erb
<h1><font size="5" class= "fire-text">Shop Or Drop</font></h1>

<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>

<style>
  h1{
    text-align:center;
  }

  body{
    background-image: url("https://media.giphy.com/media/nKERd2uhn8hhe/giphy.gif");
    background-repeat: no-repeat;
    background-color: #cccccc;
    background-size: cover;
    vertical-align: middle;
    text-align:center;
  }
 }
 </style>
  <%= render 'form' %>

app/views/buyers/index.erb
<h1> INDEX </h1>

<% @buyers.each do |buyer| %>
  <%= link_to buyer.username, buyer %><br>
<% end %>

app/views/buyers/new.erb
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>

<style>
  body{
    background-image: url("https://media.giphy.com/media/nKERd2uhn8hhe/giphy.gif");
    background-repeat: no-repeat;
    background-color: #cccccc;
    background-size: cover;
    vertical-align: middle;
    text-align:center;
  }
 }
 </style>

  <%= render 'form' %>

app/views/buyers/show.erb
<h1><font size="5" class= "fire-text">Shop Or Drop</font></h1>

<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
</head>

<style>
  body{
    background-image: url("https://media.giphy.com/media/nKERd2uhn8hhe/giphy.gif");
    background-repeat: no-repeat;
    background-color: #cccccc;
    background-size: cover;
    vertical-align: middle;
    text-align:left;
  }
  h2{
    text-align: right;
    font-size: 100%;
    }
 </style>


 <h2>
 <div class="btn-group">
 <% if session[:buyer_id] == @buyer.id %>
 <button><%= button_to "Delete Account", @buyer, method: :delete, data: { confirm: "Are you sure you want to delete your account?" } %></button>
 <button><%= button_to "Logout", logout_path, method: :delete, data: { confirm: "Are you sure you want to log out?" } %> </button>
 <% end %>
</h2>

<body>
  <% if flash[:notice] %>
    <%= flash[:notice] %>
    <% end %>

  <div>
  <ul class="columns" data-columns="1">
  <li><span style="font-weight:bold;">First Name: </span><%= @buyer.first_name %></li>
  <li><span style="font-weight:bold;">Last Name: </span><%= @buyer.last_name %> </li>
  <li> <span style="font-weight:bold;">Username: </span><%= @buyer.username %> </li>
  <li><span style="font-weight:bold;">Email: </span><%= @buyer.email %></li>
</ul>
</div>

    <h4>Your Cart: </h4>
    <%if flash[:message]%>
      <%= flash[:message] %> <br>
    <% end %>

    <%if session[:from] == "clear_cart"%>
      <%session[:cart] = [] %>
      <%session[:from] = "blank"%>
    <%else%>
        <ul class="columns" data-columns="1">
        <ol>
        <% @listings.each do |listing| %>
          <li> <%= listing.product_name %> : $<%= Listing.float_to_money(listing.product_price) %></li> <br>
        <% end %>
        </ol>
      </ul>
    <%end %>
    <button><%= link_to 'View Cart', carts_path %>  </button>
    <button><%= link_to 'Edit', edit_buyer_path %>  </button>
    <button><%= link_to 'Wish List', wishlists_path %>  </button>
    <button><%= link_to 'Swipes', swipes_path %>  </button>
    <button><%= link_to 'View Stats', buyer_stats_path %>  </button>

</body>

app/views/buyers/stats.html.erb
<h1><font size="5" class= "fire-text">Your Stats</font></h1>

<p><button><%= link_to 'Back to my page', buyer_path(session[:buyer_id]) %> <br><br></button></p>

<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
</head>

<style>
  body{
    background-image: url("https://media.giphy.com/media/nKERd2uhn8hhe/giphy.gif");
    background-repeat: no-repeat;
    background-color: #cccccc;
    background-size: cover;
    vertical-align: middle;
    text-align:left;
  }
  h2{
    text-align: right;
    font-size: 100%;
    }
    p {
      text-align: left;
    }
 </style>

 <ul class="columns" data-columns="1">
<li><span style="font-weight:bold;">Total Swipes: </span><%= @buyer.total_swipes %> </li>
<li><span style="font-weight:bold;">Total Disliked Swipes</span><%= @buyer.total_dislike_swipes %> </li>
<li><span style="font-weight:bold;">Total Liked Swipes:</span><%= @buyer.total_like_swipes %> </li>
<li><span style="font-weight:bold;">Total Superliked Swipes:</span><%= @buyer.total_superlike_swipes %> </li>
<li><span style="font-weight:bold;">Total Positive Swipes:</span><%= @buyer.total_positive_swipes %> </li>
<li><span style="font-weight:bold;">Total Percent Swipes:</span><%= @buyer.total_percent_positive %>% </li>
</ul>