config/routes.rb
Rails.application.routes.draw do
  resources :sellers
  get '/buyers/stats', to: 'buyers#stats', as: 'buyer_stats'
  resources :buyers
  resources :swipes
  resources :wishlists
  get 'sessions/new'
  resources :listings
  resources :clubs
  resources :products


  get   '/login', to: 'sessions#splash'
  patch  '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  patch '/carts', to: 'carts#update', as: 'add_listing_to_cart'
  get '/carts', to: 'carts#index', as: 'carts'
  delete '/carts', to: 'carts#destroy', as: 'clear_cart'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :buyer
  belongs_to :listing
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :find_buyer, only:[:index]
  before_action :find_wish_list, only:[:destroy]

  def index
    if !logged_in?
      redirect_to '/login'
    elsif session[:user_type] == "Seller"
      #create page saying must be logged in under a buyer account to access swipes
    end
    @wishlists = @buyer.wishlists
    wishlist_items
  end

  def show
  end

  def destroy
    @wishlist.destroy
    redirect_to wishlists_path
  end

  private
  def find_buyer
    @buyer = Buyer.find(session[:buyer_id])
  end

  def find_wish_list
    @wishlist = Wishlist.find(params[:wish_id])
  end

  def wishlist_items
    @wish_hash_array = @wishlists.map do |wish|
    {wish_id: wish.id, item: wish.listing.product_name,
      description: wish.listing.product_description,
      price: wish.listing.product_price}
    end
  end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/index.erb
<style>
  body { margin: auto;
    width: 50%;
    border: 3px solid black;
    padding: 10px;
    background-image: url("https://media.giphy.com/media/nKERd2uhn8hhe/giphy.gif");
  }
  h1{
    text-align: center;
    color: black;
  }
  p {
    color: black;
  }
  div {
    text-align: center;
  }


</style>
<body>

<h1><u>My Wishlist</u></h1>

  <p><button><%= link_to 'Back to my page', buyer_path(session[:buyer_id]) %> <br><br></button></p>
      <div>
    <% @wish_hash_array.each do |wish_hash| %>
      <p><%= wish_hash[:item] %> $<%= wish_hash[:price]%></p>
      <div class="btn-group">
      <%= button_to 'Add to Cart', add_listing_to_cart_path, { method: :patch, params: {wish_id: wish_hash[:wish_id], from: "wishlist"}} %>
      <%= button_to 'Delete Item', wishlist_path(wish_hash[:wish_id]), {method: :delete, params: {wish_id: wish_hash[:wish_id]}} %>
    <% end %>
  </div>
</div>
</body>